"""Fix ExpenseCategory relation

Revision ID: 67741c2dc571
Revises: faaf35b8f8dd
Create Date: 2025-03-04 00:03:09.569593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67741c2dc571"
down_revision: Union[str, None] = "faaf35b8f8dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
