"""Fix ExpenseCategory relation

Revision ID: b06f88713992
Revises: e5fd1066d47f
Create Date: 2025-03-03 19:19:51.142403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b06f88713992"
down_revision: Union[str, None] = "e5fd1066d47f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
