"""Fix ExpenseCategory relation

Revision ID: faaf35b8f8dd
Revises: b06f88713992
Create Date: 2025-03-03 23:48:13.323851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "faaf35b8f8dd"
down_revision: Union[str, None] = "b06f88713992"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
